name: Release Php SDK

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version of the SDK that you would like to release"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v4

      - name: Install pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0

      - name: Download Fern
        run: pnpm add -g fern-api@5.65.3

      - name: Release SDKs
        env:
          FERN_TOKEN: ${{ secrets.FERN_TOKEN }}
        run: |
          fern generate --group php-sdk --version ${{ inputs.version }} --log-level debug