paths:
  '/articles':
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateArticleRequestBody'
  '/articles/{id}':
    put: null
  '/tickets':
    post: null
  '/ticket_types/{id}':
    put: null
  '/export/reporting_data/{job_identifier}':
    get: null
  '/download/reporting_data/{job_identifier}':
    get: null
  '/companies':
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrUpdateCompanyRequestBody'
  '/phone_call_redirects':
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePhoneSwitchRequestBody'
  '/ticket_types':
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTicketTypeRequestBody'
  '/contacts/{id}/companies':
    post:
      requestBody:
        content:
          application/json:
            schema:
              required:
                - company_id
              properties:
                company_id:
                  type: string
                  description: The unique identifier for the company which is given
                    by Intercom
                  example: 58a430d35458202d41b1e65b
                id: null
            examples:
              successful:
                summary: Successful
                value:
                  company_id: 6762f09a1bb69f9f2193bb34
              bad_request:
                summary: Bad Request
                value:
              company_not_found:
                summary: Company Not Found
                value:
                  company_id: '123'
  '/messages/status':
    get:
      responses:
        '500':
          content:
            application/json:
              examples: null
  '/custom_channel_events/notify_attribute_collected':
    post:
      x-fern-sdk-group-name:
        - customChannelEvents
      x-fern-sdk-method-name: notifyAttributeCollected
      x-fern-request-name: NotifyAttributeCollectedRequest
  '/custom_channel_events/notify_new_message':
    post:
      x-fern-sdk-group-name:
        - customChannelEvents
      x-fern-sdk-method-name: notifyNewMessage
      x-fern-request-name: NotifyNewMessageRequest
  '/custom_channel_events/notify_new_conversation':
    post:
      x-fern-sdk-group-name:
        - customChannelEvents
      x-fern-sdk-method-name: notifyNewConversation
      x-fern-request-name: NotifyNewConversationRequest
  '/custom_channel_events/notify_quick_reply_selected':
    post:
      x-fern-sdk-group-name:
        - customChannelEvents
      x-fern-sdk-method-name: notifyQuickReplySelected
      x-fern-request-name: NotifyQuickReplySelectedRequest
  '/internal_articles/{id}':
    put:
      x-fern-sdk-group-name:
        - internalArticles
      x-fern-sdk-method-name: update
      x-fern-request-name: UpdateInternalArticleBodyRequest

components:
  schemas:
    custom_attributes:
      example:
        monthly_spend: '155.5'
    create_ticket_request:
      x-fern-type-name: CreateTicketRequestBody
      properties:
        ticket_attributes: null
    reply_conversation_request:
      x-fern-type-name: ReplyConversationRequestBody
    update_article_request:
      x-fern-type-name: UpdateArticleRequestBody
    update_ticket_type_request:
      x-fern-type-name: UpdateTicketTypeRequestBody
    single_filter_search_request:
      properties:
        operator:
          enum:
            - '='
            - '!='
            - IN
            - NIN
            - '<'
            - '>'
