name: Deploy openapi spec to readme
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install
      - name: Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v35
      - run: node ./scripts/run-sync.js ${{ steps.changed-files.outputs.all_changed_and_modified_files }} ${{ secrets.README_API_KEY }}
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_and_modified_files }}; do
            echo "$file was changed"
          done
