name: Post to PR feed

on:
  pull_request:
    types:
      - review_requested

jobs:
  call-pr-feed-workflow:
    uses: intercom/github-action-workflows/.github/workflows/post-to-pr-feed.yml@main
    secrets: inherit
